# Generated by Django 3.2 on 2023-12-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='petorders',
            fields=[
                ('Breed_name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('cus_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone', models.CharField(default='SOME STRING', max_length=50)),
            ],
        ),
    ]
